{"name": "Login_01 : Verify that a user can log in with valid credentials", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 60000ms exceeded.\nCall log:\n  - navigating to \"https://149.255.39.63/\", waiting until \"load\"", "trace": "self = <tests.Login.test_Login.TestLogin object at 0x0000023E8C7947A0>, setup = <Page url='about:blank'>\nconfig = <class 'utilities.config.config_stage.Config'>\n\n    @allure.title(\"Login_01 : Verify that a user can log in with valid credentials\")\n    def test_login(self, setup, config):\n        page = setup\n        login_page = LoginPage(page)\n    \n>       login_page.navigate(config.BASE_URL)\n\ntests\\Login\\test_Login.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\base_page.py:23: in navigate\n    self.page.goto(url)\n..\\..\\..\\AppData\\Roaming\\Python\\Python312\\site-packages\\playwright\\sync_api\\_generated.py:9020: in goto\n    self._sync(\n..\\..\\..\\AppData\\Roaming\\Python\\Python312\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n..\\..\\..\\AppData\\Roaming\\Python\\Python312\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n..\\..\\..\\AppData\\Roaming\\Python\\Python312\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x0000023E8C855DF0>, cb = <function Channel.send.<locals>.<lambda> at 0x0000023E8C8B7A60>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 60000ms exceeded.\nE           Call log:\nE             - navigating to \"https://149.255.39.63/\", waiting until \"load\"\n\n..\\..\\..\\AppData\\Roaming\\Python\\Python312\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "attachments": [{"name": "Log", "source": "dc7585bf-06bb-4139-8c70-e779790582ba-attachment.txt", "type": "text/plain"}, {"name": "Screenshot", "source": "22e622f8-9b6e-49af-98dc-075116b14a73-attachment.png", "type": "image/png"}], "start": 1743745013909, "stop": 1743745073945, "uuid": "111e7866-113d-4884-a068-a14cd91598ec", "historyId": "0b71423287f2d4d074dd395368b2c44c", "testCaseId": "0b71423287f2d4d074dd395368b2c44c", "fullName": "tests.Login.test_Login.TestLogin#test_login", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.Login"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PavanKarri"}, {"name": "thread", "value": "9172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Login.test_Login"}]}