{"name": "create Group", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at https://149.255.39.63/\nCall log:\n  - navigating to \"https://149.255.39.63/\", waiting until \"load\"", "trace": "self = <tests.User.test_TC01_createGroup.TestTC01 object at 0x000002AFC50AFD40>, setup = <Page url='about:blank'>\nconfig = <class 'utilities.config.config_stage.Config'>\n\n    @allure.title(\"create Group\")\n    def test_crate_group(self, setup, config):\n        page = setup\n        home_page = HomePage(page)\n        login_page = LoginPage(page)\n        user_page = UserPage(page)\n        group_page = GroupsPage(page)\n        filter_page = FilterPage(page)\n    \n        groupName = RandomUtils.get_last_name()\n        permissionsList = [\"group\", \"user\", \"filter\", \"job\", \"notifications\", \"Settings\", \"System Configuration\"]\n    \n    \n>       login_page.navigate(config.BASE_URL)\n\ntests\\User\\test_TC01_createGroup.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\base_page.py:23: in navigate\n    self.page.goto(url)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9018: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:551: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002AFC7ED0590>, cb = <function Channel.send.<locals>.<lambda> at 0x000002AFC833A020>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at https://149.255.39.63/\nE           Call log:\nE             - navigating to \"https://149.255.39.63/\", waiting until \"load\"\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: Error"}, "attachments": [{"name": "Log", "source": "324c1d61-e855-49ff-939e-22fd0ffce8e5-attachment.txt", "type": "text/plain"}, {"name": "Screenshot", "source": "0e8a5a80-f7df-492e-9d23-c8fa565712f8-attachment.png", "type": "image/png"}], "start": 1742465357138, "stop": 1742465360516, "uuid": "06ef4a0a-182d-4cbd-aef9-3f92c1a90f51", "historyId": "9d56ea0aa81bcdebf1331156ba14a8a1", "testCaseId": "9d56ea0aa81bcdebf1331156ba14a8a1", "fullName": "tests.User.test_TC01_createGroup.TestTC01#test_crate_group", "labels": [{"name": "suite", "value": "Group Permissions"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.User"}, {"name": "subSuite", "value": "TestTC01"}, {"name": "host", "value": "Pavan-Karri"}, {"name": "thread", "value": "29040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.User.test_TC01_createGroup"}]}