{"name": "create user", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at https://149.255.39.63/\nCall log:\n  - navigating to \"https://149.255.39.63/\", waiting until \"load\"", "trace": "self = <tests.User.test_TC02_createUser.TestTC02 object at 0x000002AFC7FA0CB0>, setup = <Page url='about:blank'>\nconfig = <class 'utilities.config.config_stage.Config'>\n\n    @allure.title(\"create user\")\n    def test_create_user(self, setup, config):\n        page = setup\n        home_page = HomePage(page)\n        login_page = LoginPage(page)\n        user_page = UserPage(page)\n        filter_page = FilterPage(page)\n    \n        userName = RandomUtils.get_user_name()\n        firstName = RandomUtils.get_first_name()\n        lastName = RandomUtils.get_last_name()\n        email = RandomUtils.get_email()\n    \n>       login_page.navigate(config.BASE_URL)\n\ntests\\User\\test_TC02_createUser.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\base_page.py:23: in navigate\n    self.page.goto(url)\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9018: in goto\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:551: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000002AFC832A540>, cb = <function Channel.send.<locals>.<lambda> at 0x000002AFCA2CC860>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: Page.goto: net::ERR_CONNECTION_REFUSED at https://149.255.39.63/\nE           Call log:\nE             - navigating to \"https://149.255.39.63/\", waiting until \"load\"\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: Error"}, "attachments": [{"name": "Log", "source": "de28d332-8e4c-41b7-966d-51bd5996baa2-attachment.txt", "type": "text/plain"}, {"name": "Screenshot", "source": "480af7f0-f5a1-4e21-8655-04f0aa9cdb5f-attachment.png", "type": "image/png"}], "start": 1742465363529, "stop": 1742465367054, "uuid": "f53189b0-3c44-4955-9f44-f13f0873e86e", "historyId": "070cd8cfeaa94bfced5d142c74f34afe", "testCaseId": "070cd8cfeaa94bfced5d142c74f34afe", "fullName": "tests.User.test_TC02_createUser.TestTC02#test_create_user", "labels": [{"name": "suite", "value": "User Management"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.User"}, {"name": "subSuite", "value": "TestTC02"}, {"name": "host", "value": "Pavan-Karri"}, {"name": "thread", "value": "29040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.User.test_TC02_createUser"}]}